export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ADD_USER = 'ADD_USER';
export const GET_ENGINEERS = 'GET_ENGINEERS';
export const CREATE_LF = 'CREATE_LF';
export const CREATE_LF_ERROR = 'CREATE_LF_ERROR';
export const CLEAR_DATA = 'CLEAR_DATA';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';
export const FETCH_ENGINEER = 'FETCH_ENGINEER';
export const MY_ENGINEERS = 'MY_ENGINEERS';
export const REMOVE_ENGINEERS = 'REMOVE_ENGINEERS';
export const REPLACE_ENGINEERS = 'REPLACE_ENGINEERS';
export const SAVE_ENGINEERS = 'SAVE_ENGINEERS';
export const GET_USERS = 'GET_USERS';
export const ADD_ENGINEER = 'ADD_ENGINEER';
export const REDIRECT_USER = 'REDIRECT_USER';
export const RATE_ENGINEER_SUCCESS = 'RATE_ENGINEER_SUCCESS';
export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
export const FETCH_RATING = 'FETCH_RATING';
export const AVERAGE_RATING = 'AVERAGE_RATING';
export const FAILED_RATING_ALL = 'FAILED_RATING_ALL';

export const FETCH_EMAILS_LOADING = 'FETCH_EMAILS_LOADING';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_ERROR = 'FETCH_EMAILS_ERROR';

export const ADD_EMAILS_LOADING = 'ADD_EMAILS_LOADING';
export const ADD_EMAILS_SUCCESS = 'ADD_EMAILS_SUCCESS';
export const ADD_EMAILS_ERROR = 'ADD_EMAILS_ERROR';

export const REMOVE_EMAILS_LOADING = 'REMOVE_EMAILS_LOADING';
export const REMOVE_EMAILS_SUCCESS = 'REMOVE_EMAILS_SUCCESS';
export const REMOVE_EMAILS_ERROR = 'REMOVE_EMAILS_ERROR';
export const SELECTED_COHORT = 'SELECTED_COHORT';
export const SELECTED_PROGRAM = 'SELECTED_PROGRAM';
export const CHANGE_PROGRAM = 'CHANGE_PROGRAM';
export const UPDATE_ENGINEER_COHORT = 'UPDATE_ENGINEER_COHORT';
export const GET_COHORTS = 'GET_COHORTS';
export const ADD_COHORT = 'ADD_COHORT';
export const REMOVE_COHORT = 'REMOVE_COHORT';
export const ADD_PROGRAM = 'ADD_PROGRAM';
export const REMOVE_PROGRAM = 'REMOVE_PROGRAM';
export const UPDATE_PROGRAM = 'UPDATE_PROGRAM';
export const UPDATE_COHORT = 'UPDATE_COHORT';
export const FETCHING_COHORTS = 'FETCHING_COHORTS';
export const FETCHING_COHORTS_SUCCESS = 'FETCHING_COHORTS_SUCCESS';
export const FETCHING_COHORTS_FAILED = 'FETCHING_COHORTS_FAILED';
export const FETCHING_PROGRAMS = 'FETCHING_PROGRAMS';
export const FETCHING_PROGRAMS_SUCCESS = 'FETCHING_PROGRAMS_SUCCESS';
export const FETCHING_PROGRAMS_FAILED = 'FETCHING_PROGRAMS_FAILED';
export const FETCHING_ATTENDANCE = 'FETCHING_ATTENDANCE';
export const FETCHING_ATTENDANCE_SUCCESS = 'FETCHING_ATTENDANCE_SUCCESS';
export const FETCHING_ATTENDANCE_FAILED = 'FETCHING_ATTENDANCE_FAILED';

export const CREATING_SESSIONS = 'CREATING_SESSIONS';
export const CREATING_SESSIONS_SUCCESS = 'CREATING_SESSIONS_SUCCESS';
export const CREATING_SESSIONS_FAILED = 'CREATING_SESSIONS_FAILED';

export const FETCHING_SESSIONS = 'FETCHING_SESSIONS';
export const FETCHING_SESSIONS_SUCCESS = 'FETCHING_SESSIONS_SUCCESS';
export const FETCHING_SESSIONS_FAILED = 'FETCHING_SESSIONS_FAILED';

export const DELETING_SESSIONS = 'DELETING_SESSIONS';
export const DELETING_SESSIONS_SUCCESS = 'DELETING_SESSIONS_SUCCESS';
export const DELETING_SESSIONS_FAILED = 'DELETING_SESSIONS_FAILED';

export const FETCH_ALL_USERS_PENDING = 'FETCH_ALL_USERS_PENDING';
export const FTECH_ALL_USER_SUCCESS = 'FTECH_ALL_USER_SUCCESS';
export const FETCH_ALL_USERS_FAILED = 'FETCH_ALL_USERS_FAILED';

export const EXPORT_TRAINEE_RATINGS_PENDING = 'EXPORT_TRAINEE_RATINGS_PENDING';
export const EXPORT_TRAINEE_RATINGS_SUCCESS = 'EXPORT_TRAINEE_RATINGS_SUCCESS';
export const EXPORT_TRAINEE_RATINGS_FAILED = 'EXPORT_TRAINEE_RATINGS_FAILED';
