export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ADD_USER = 'ADD_USER';
export const GET_ENGINEERS = 'GET_ENGINEERS';
export const CREATE_LF = 'CREATE_LF';
export const CREATE_LF_ERROR = 'CREATE_LF_ERROR';
export const CLEAR_DATA = 'CLEAR_DATA';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';
export const FETCH_ENGINEER = 'FETCH_ENGINEER';
export const MY_ENGINEERS = 'MY_ENGINEERS';
export const REMOVE_ENGINEERS = 'REMOVE_ENGINEERS';
export const REPLACE_ENGINEERS = 'REPLACE_ENGINEERS';
export const SAVE_ENGINEERS = 'SAVE_ENGINEERS';
export const GET_USERS = 'GET_USERS';
export const ADD_ENGINEER = 'ADD_ENGINEER';
export const REDIRECT_USER = 'REDIRECT_USER';
export const RATE_ENGINEER_SUCCESS =
  'RATE_ENGINEER_SUCCESS';
export const UPDATE_RATING_SUCCESS =
  'UPDATE_RATING_SUCCESS';
export const FETCH_RATING = 'FETCH_RATING';

export const FETCH_EMAILS_LOADING = 'FETCH_EMAILS_LOADING';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_ERROR = 'FETCH_EMAILS_ERROR';

export const ADD_EMAILS_LOADING = 'ADD_EMAILS_LOADING';
export const ADD_EMAILS_SUCCESS = 'ADD_EMAILS_SUCCESS';
export const ADD_EMAILS_ERROR = 'ADD_EMAILS_ERROR';

export const REMOVE_EMAILS_LOADING = 'REMOVE_EMAILS_LOADING';
export const REMOVE_EMAILS_SUCCESS = 'REMOVE_EMAILS_SUCCESS';
export const REMOVE_EMAILS_ERROR = 'REMOVE_EMAILS_ERROR';
